language: php
php:
  - '7.2.17'
before_script:
    - if [ -d "./.idea" ]; then echo "Forbidden idea folder found !"; exit 2; fi
    - if [ -d "./.env.local" ]; then echo "Forbidden configuration file found !"; exit 2; fi
    - if [ -d "./node_modules" ]; then echo "Forbidden node_modules folder found !"; exit 2; fi
    - if [ -d "./public/build" ]; then echo "Forbidden public/build folder found !"; exit 2; fi
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install build-essential git -y
  - git clone -b stable https://github.com/jedisct1/libsodium.git
  - cd libsodium && sudo ./configure && sudo make check && sudo make install && cd ..
  - '[[ "$TRAVIS_PHP_VERSION" == "nightly" ]] || phpenv config-rm xdebug.ini'
  - composer self-update
install:
  - pecl install libsodium
  - echo "extension=sodium.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer require squizlabs/php_codesniffer 3.2
cache:
  yarn: true
  directories:
    - $HOME/.composer/cache/files
script:
- vendor/bin/phpcs --standard=PSR2 --ignore=src/Migrations src/
- vendor/bin/php-cs-fixer fix --diff --dry-run -v
- vendor/bin/phpstan analyse src/Command src/Controller src/Entity src/Form src/Repository src/Security src/Service src/EventSubscriber src/Events.php --level 1
